working pre-commit hook

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,50 +1,52 @@
-#!/bin/bash
+#!/bin/sh
 
-HAS_NODE=`which node 2> /dev/null || which nodejs 2> /dev/null || which iojs 2> /dev/null`
+BRANCH=$(git rev-parse --abbrev-ref HEAD)
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
+JSHINT=$(git diff --cached --name-only --diff-filter=ACM | grep "\.js$")
+PASS=true
 
-#
-# There are some issues with Source Tree because paths are not set correctly for
-# the given environment. Sourcing the bash_profile seems to resolve this for bash users,
-# sourcing the zshrc for zshell users.
-#
-# https://answers.atlassian.com/questions/140339/sourcetree-hook-failing-because-paths-don-t-seem-to-be-set-correctly
-#
-function source_home_file {
-  file="$HOME/$1"
-  [[ -f "${file}" ]] && source "${file}"
-}
-
-if [[ -z "$HAS_NODE" ]]; then
-  source_home_file ".bash_profile" || source_home_file ".zshrc" || true
-fi
-
-NODE=`which node 2> /dev/null`
-NODEJS=`which nodejs 2> /dev/null`
-IOJS=`which iojs 2> /dev/null`
-LOCAL="/usr/local/bin/node"
-BINARY=
-
-#
-# Figure out which binary we need to use for our script execution.
-#
-if [[ -n "$NODE" ]]; then
-  BINARY="$NODE"
-elif [[ -n "$NODEJS" ]]; then
-  BINARY="$NODEJS"
-elif [[ -n "$IOJS" ]]; then
-  BINARY="$IOJS"
-elif [[ -x "$LOCAL" ]]; then
-  BINARY="$LOCAL"
-fi
-
-#
-# Add --dry-run cli flag support so we can execute this hook without side affects
-# and see if it works in the current environment
-#
-if [[ $* == *--dry-run* ]]; then
-  if [[ -z "$BINARY" ]]; then
-    exit 1
-  fi
+if [[ "$BRANCH" == "master" || "$BRANCH" == "develop" ]]; then
+  echo "You are on branch $BRANCH. Are you sure you want to commit to this branch?"
+  echo "If so, commit with -n to bypass this pre-commit hook."
+  exit 1
 else
-  "$BINARY" "$("$BINARY" -e "console.log(require.resolve('pre-commit'))")"
+  echo "You're on $BRANCH. Yay!"
+fi
+# echo "\nValidating Javascript:\n"
+# Check for eslint
+which eslint &> /dev/null
+if [[ "$?" == 1 ]]; then
+  echo "\t\033[41mPlease install ESlint\033[0m"
+  exit 1
+fi
+
+for FILE in $STAGED_FILES
+do
+  eslint --max-warnings 900 "$FILE"
+
+  if [[ "$?" == 1 ]]; then
+    PASS=false
+  fi
+done
+
+# for FILE in $JSHINT
+# do
+#   echo "Testing: $FILE"
+#   jshint "$FILE"
+
+#   if [[ "$?" == 0 ]]; then
+#     echo "\t\033[32mESLint Passed: $FILE\033[0m"
+#   else
+#     echo "\t\033[41mJSHint Failed: $FILE\033[0m"
+#     PASS=false
+#   fi
+# done
+
+
+# echo "\nJavascript validation completed!\n"​
+if ! $PASS; then
+  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
+  exit 1
+else
+  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
 fi
